openapi: 3.0.3
info:
  title: Navigation API
  description: API endpoints for navigation state and theme management
  version: 1.0.0
  contact:
    name: Mafia Insight Team
    email: dev@mafiainsight.com

servers:
  - url: /api/navigation
    description: Navigation API endpoints

paths:
  /state:
    get:
      summary: Get navigation state
      description: Get current user's navigation state and visible pages
      tags:
        - Navigation
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Navigation state retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NavigationState'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update navigation state
      description: Update current user's navigation state
      tags:
        - Navigation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                activePage:
                  type: string
                  example: 'players'
      responses:
        '200':
          description: Navigation state updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NavigationState'
        '401':
          description: Unauthorized
        '422':
          description: Validation error

  /pages:
    get:
      summary: Get available pages
      description: Get all pages available to current user based on permissions
      tags:
        - Navigation
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Available pages retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  pages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Page'
        '401':
          description: Unauthorized

  /theme:
    get:
      summary: Get theme preference
      description: Get current user's theme preference
      tags:
        - Theme
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Theme preference retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThemePreference'
        '401':
          description: Unauthorized

    put:
      summary: Update theme preference
      description: Update current user's theme preference
      tags:
        - Theme
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - theme
              properties:
                theme:
                  type: string
                  enum: [light, dark, system]
                  example: 'dark'
      responses:
        '200':
          description: Theme preference updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThemePreference'
        '401':
          description: Unauthorized
        '422':
          description: Validation error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    NavigationState:
      type: object
      properties:
        userId:
          type: string
          nullable: true
          example: 'user_123'
        activePage:
          type: string
          example: 'players'
        visiblePages:
          type: array
          items:
            type: string
          example: ['home', 'players', 'analytics']
        lastUpdated:
          type: string
          format: date-time

    Page:
      type: object
      properties:
        id:
          type: string
          example: 'players'
        name:
          type: string
          example: 'Players'
        path:
          type: string
          example: '/players'
        icon:
          type: string
          example: 'users'
        requiresAuth:
          type: boolean
          example: true
        requiredPermissions:
          type: array
          items:
            type: string
          example: ['read:players']

    ThemePreference:
      type: object
      properties:
        userId:
          type: string
          nullable: true
          example: 'user_123'
        theme:
          type: string
          enum: [light, dark, system]
          example: 'dark'
        updatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: 'Navigation error'
        message:
          type: string
          example: 'Unable to load navigation state'
        code:
          type: string
          example: 'NAVIGATION_ERROR'
